version: "3"

services:

  web:
    container_name: django-docker
    build: .
    env_file: .env
    command: python /code/manage.py runserver 0.0.0.0:8000
    working_dir: /code
    volumes:
        - .:/code:z
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: django-docker-db
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    env_file: .env
    restart: always
    volumes:
      - django_data:/bitnami/postgresql

volumes:
  django_data:

# This is to allow docker to work properly on a VPN.
# Can be safely removed if not needed
networks:
  default:
    external:
      name: localdev
